// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Byrth.Core.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rebuild : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rebuild));
        
        string IMigrationMetadata.Id
        {
            get { return "201509141529134_Rebuild"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
